- .github/workflows/main.yaml
- .github/workflows/pypi-publish.yaml
- README.md
- pyproject.toml
Trivial updates to certain files to help improve and better facilitate the release process.
> oaklib release infrastructure support

- poetry.lock
Bumped up the version for the `sssom`dependency.
> ran `poetry update sssom`

- src/oaklib/cli.py
- src/oaklib/datamodels/lexical_index.py
- src/oaklib/datamodels/ontology_metadata.py
- src/oaklib/datamodels/ontology_metadata.yaml
- src/oaklib/datamodels/validation_datamodel.py
- src/oaklib/datamodels/validation_datamodel.yaml
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/validator_interface.py
- tests/test_cli.py
- Fix bug with SQL LIKE constraint (underscore matches any character) Refactored lexical tests
- allow custom schema for ontology metadata validation
> custom schema

- .github/workflows/doc_pages.yaml
- poetry.lock
- pyproject.toml
Fixes #14 
This is how this works:
The documentation files will be hosted in the `gh-pages` branch and it will be deployed only when a PR is merged to the main branch. The `docs` folder  in the main branch hosts all the `*.rst` files needed by sphinx to generate the documentation.
> poetry update + tested workflow for sphinx deployment in gh-pages

- docs/cli.rst
- docs/interfaces/search.rst
- docs/search-syntax.rst
- src/oaklib/datamodels/search.py
- Refactored search
- search-docs
> search docs

- src/oaklib/cli.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/search_interface.py
- src/oaklib/io/streaming_info_writer.py
- src/oaklib/io/streaming_obo_writer.py
- src/oaklib/io/streaming_writer.py
- src/oaklib/utilities/lexical/lexical_indexer.py
- tests/test_cli.py
- tests/test_utilities/test_roll_up_to_subset.py
- fixing CLI docs
- adding additional CURIE check, fixes #64 Added display options for some commands.
> cli input arg

- src/oaklib/implementations/bioportal/bioportal_implementation.py
This allows running a search like so:
```
runoak -i bioportal:snomedct search asthma
```
> Allow BioPortal search to be limited to one ontology

- src/oaklib/cli.py
- src/oaklib/datamodels/cross_ontology_diff.py
- src/oaklib/datamodels/cross_ontology_diff.yaml
- src/oaklib/datamodels/similarity.py
- src/oaklib/datamodels/similarity.yaml
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/implementations/ubergraph/ubergraph_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/interfaces/semsim_interface.py
- src/oaklib/utilities/graph/networkx_bridge.py
- src/oaklib/utilities/obograph_utils.py
- tests/test_implementations/test_sqldb.py
From hacking session with Jules, Mark, Justin, Harshad
> Adding phenodigm score to SemSim datamodel and ubergraph implementation.

- .github/workflows/doc_pages.yaml
> added linkml based docs in gh-action workflow

- README.md
> Fix CLI examples

- src/oaklib/cli.py
- src/oaklib/datamodels/vocabulary.py
- src/oaklib/interfaces/semsim_interface.py
- src/oaklib/utilities/graph/networkx_bridge.py
- src/oaklib/utilities/obograph_utils.py
- tests/test_implementations/test_sqldb.py
- Adding phenodigm score to SemSim datamodel and ubergraph implementation.
- Adding phenodigm score to SemSim datamodel and ubergraph implementation.
- Additional SQLite tests for mutability
- adding missing
- Adding ability to include MRCAs in viz prior to gap-fill step. Additional tests for MRCA methods
> Adding ability to include MRCAs in viz prior to gap-fill step. Additional tests for MRCA methods

- README.md
> Fix zenodo badge

- docs/glossary.rst
- poetry.lock
- pyproject.toml
- src/oaklib/cli.py
- src/oaklib/datamodels/similarity.yaml
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/semsim_interface.py
- tests/test_implementations/test_pronto.py
See https://github.com/monarch-initiative/monarch-semsim/issues/1
HPO all by all takes ~20 mins on a laptop.
> Made all by all similarity more efficient

- src/oaklib/cli.py
- tests/test_cli.py
- refactored query iterator
- Adding nesting of search terms
> refactor query term iterator

- src/oaklib/cli.py
- src/oaklib/conf/obograph-style.json
- src/oaklib/implementations/wikidata/wikidata_implementation.py
- src/oaklib/interfaces/obograph_interface.py
- src/oaklib/io/streaming_csv_writer.py
- src/oaklib/io/streaming_info_writer.py
- src/oaklib/io/streaming_json_writer.py
- src/oaklib/io/streaming_obo_json_writer.py
- src/oaklib/io/streaming_obo_writer.py
- src/oaklib/io/streaming_owl_functional_writer.py
- src/oaklib/io/streaming_rdf_writer.py
- src/oaklib/io/streaming_writer.py
- src/oaklib/utilities/obograph_utils.py
- tests/test_cli.py
Fixes #147 
Started unifying command structure, see #145
term-mappings deleted: use mappings
This also streamlines the formatting for most commands
These are the types; not all types apply to all commands:
OBO_FORMAT = "obo"
RDF_FORMAT = "rdf"
MD_FORMAT = "md"
OBOJSON_FORMAT = "obojson"
CSV_FORMAT = "csv"
JSON_FORMAT = "json"
JSONL_FORMAT = "jsonl"
YAML_FORMAT = "yaml"
INFO_FORMAT = "info"
SSSOM_FORMAT = "sssom"
OWLFUN_FORMAT = "ofn"
Examples:
```
$ runoak -i bioportal:ceph annotate "tentacle squid head" -O rdf
@prefix ns1: <https://w3id.org/linkml/text_annotator/> .
@prefix ns2: <http://w3id.org/sssom/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
[] a <http://www.w3.org/ns/oa#Annotation> ;
ns2:object_id "CEPH:0000256" ;
ns2:object_label "tentacle" ;
ns2:object_source …
```
> Added RDF streaming writer and allow it as option for most RDF commands. Fixes #147

- src/oaklib/implementations/bioportal/__init__.py
- src/oaklib/implementations/bioportal/bioportal_implementation.py
- src/oaklib/implementations/ols/__init__.py
- src/oaklib/implementations/ols/ols_implementation.py
- src/oaklib/implementations/sparql/__init__.py
- src/oaklib/implementations/sparql/abstract_sparql_implementation.py
- src/oaklib/implementations/sqldb/__init__.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/implementations/wikidata/__init__.py
- src/oaklib/implementations/wikidata/wikidata_implementation.py
- tox.ini
> Address pending flake8 rules

- README.md
- Updates: README.md: (i) reorganized/added 'dev' section, (ii) added project setup steps.
> Documentation for dev/setup

- src/oaklib/cli.py
- tests/test_cli.py
> Get `mappings` from `mapping_input` using `SSSOM-py`

- src/oaklib/cli.py
> ensuring the correct logger is used when setting verbosity

- notebooks/Command-Line-Examples.ipynb
- src/oaklib/cli.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/obograph_interface.py
- src/oaklib/io/obograph_writer.py
- tests/test_cli.py
- demonstrating boolean term search queries
- demonstarting KGCL
Separating logic for writing graphs into a seperate writer package.
Fixing bug in which graphs could not be written in obo format on stdout
> Adding a new notebook example

- src/oaklib/utilities/lexical/lexical_indexer.py
> Fixed docstring

- src/oaklib/implementations/pronto/pronto_implementation.py
> New synonym request handling  for `ProntoImplementation`

- src/oaklib/implementations/ontoportal/ontoportal_implementation_base.py
- src/oaklib/interfaces/basic_ontology_interface.py
- tests/test_implementations/test_bioportal.py
Fixes #251 
with help from @pkalita-lbl and @hrshdhgd 
This also adds a uri fallback
> Fixing bioportal curie contraction. Fixes #251

- src/oaklib/resource.py
- tests/test_implementations/test_ubergraph.py
> Making local=False the default again

- notebooks/Monarch/PhenIO-Tutorial.ipynb
- src/oaklib/implementations/__init__.py
- src/oaklib/implementations/bioportal/__init__.py
- src/oaklib/implementations/ontoportal/agroportal_implementation.py
- src/oaklib/implementations/ontoportal/bioportal_implementation.py
- src/oaklib/implementations/ontoportal/ecoportal_implementation.py
- src/oaklib/implementations/ontoportal/matportal_implementation.py
- src/oaklib/implementations/ontoportal/ontoportal_implementation_base.py
- src/oaklib/selector.py
- tests/test_implementations/test_bioportal.py
> Added additional ontoportal clients and refactored location.

- src/oaklib/cli.py
- src/oaklib/implementations/__init__.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_parser.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/selector.py
- tests/test_implementations/test_simple_obo.py
> First pass at simple obo parser.

- .github/workflows/main.yaml
- src/oaklib/utilities/mapping/cross_ontology_diffs.py
~from collections import Iterator, defaultdict~
```
from collections import defaultdict
from collections.abc import Iterator
```
> Change collections import to abide by new package design

- src/oaklib/implementations/__init__.py
- src/oaklib/selector.py
> Add discovered plugins to implementation resolver

- src/oaklib/cli.py
- src/oaklib/datamodels/similarity.py
- src/oaklib/datamodels/similarity.yaml
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/implementations/ubergraph/ubergraph_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/interfaces/relation_graph_interface.py
- src/oaklib/interfaces/semsim_interface.py
- src/oaklib/io/heatmap_writer.py
- src/oaklib/io/streaming_writer.py
- tests/test_cli.py
- tests/test_implementations/test_sqldb.py
- tests/test_implementations/test_ubergraph.py
Renaming "similarity" command to "similarity-pair"
Added a heatmap output
> Adding a --include-entailed option for relationships.

- notebooks/OntologyEditorsGuide/Edit-File-Examples.ipynb
- src/oaklib/cli.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_parser.py
- src/oaklib/implementations/sparql/abstract_sparql_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/interfaces/differ_interface.py
- src/oaklib/interfaces/obograph_interface.py
- src/oaklib/io/streaming_json_writer.py
- src/oaklib/io/streaming_kgcl_writer.py
- src/oaklib/utilities/graph/relationship_walker.py
- src/oaklib/utilities/lexical/lexical_indexer.py
- src/oaklib/utilities/ontology_builder.py
- tests/test_cli.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_simple_obo.py
- tests/test_utilities/test_cross_ontology_diff.py
- tests/test_utilities/test_lexical_index.py
- tests/test_utilities/test_ontology_builder.py
- Ensuring pipeline transformations are cumulative. Fixes #274
- Test for #274
- Adding a builder class
- fixing inefficiencies
- KGCL enhancements
- Adding test
- lint
> Additional KGCL functionality and fix for #274

- src/oaklib/cli.py
- src/oaklib/implementations/sparql/abstract_sparql_implementation.py
- src/oaklib/implementations/sparql/sparql_query.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- tests/test_cli.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_sparql.py
- tests/test_implementations/test_sqldb.py
- Add option to filter owl tautologies
- Raise exception if path to sqlite db does not exist, fixes #90
- moving towards general compliance suite, #291
- Renaming check-definitions to validate-definitions. #30
- ability to filter owl tautologies.
> Enhancing tests, moving towards compliance framework

- docs/howtos/write-a-plugin.rst
> Update documentation on plugin entry points

- src/oaklib/cli.py
- src/oaklib/datamodels/search.py
- src/oaklib/datamodels/search_datamodel.yaml
- src/oaklib/datamodels/vocabulary.py
- src/oaklib/implementations/sparql/abstract_sparql_implementation.py
- src/oaklib/implementations/ubergraph/ubergraph_implementation.py
- src/oaklib/implementations/uniprot/uniprot_implementation.py
- src/oaklib/selector.py
- src/oaklib/utilities/mapping/cross_ontology_diffs.py
- tests/test_cli.py
> Adding uniprot adapter.

- src/oaklib/datamodels/vocabulary.py
- src/oaklib/implementations/obograph/obograph_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/obograph_interface.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_sqldb.py
- Implementing as_obograph. Fixes #321
- obograph roundtripping.
> Implement obograph dumper for sql_implementation, fixes #321

- src/oaklib/datamodels/vocabulary.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_parser.py
- tests/test_implementations/__init__.py
Implemented `NodeObsoletionWithDirectReplacement` within `NodeObsoletion`
> Implement NodeObsoletionWithDirectReplacement in simpleobo implementation

- poetry.lock
- pyproject.toml
- src/oaklib/cli.py
- src/oaklib/utilities/table_filler.py
- tests/test_utilities/test_table_filler.py
> `fill_table` now handles comments in tsv file.

- .gitignore
- poetry.lock
- pyproject.toml
- src/oaklib/cli.py
- src/oaklib/datamodels/text_annotator.py
- src/oaklib/datamodels/text_annotator.yaml
- src/oaklib/interfaces/text_annotator_interface.py
- src/oaklib/utilities/ner_utilities.py
- tests/input/exclude.txt
- tests/input/matcher-text.txt
- tests/test_cli.py
> Passing a exclusion list to `annotate` CLI

- docs/converters/data-model-converter.rst
- docs/converters/index.rst
- docs/converters/obo-graph-to-fhir.rst
- docs/converters/obo-graph-to-owl.rst
- docs/datamodels/index.rst
- docs/index.rst
- src/oaklib/converters/data_model_converter.py
- src/oaklib/converters/obo_graph_to_fhir_converter.py
- src/oaklib/datamodels/fhir.yaml
- src/oaklib/datamodels/search.py
- src/oaklib/datamodels/search_datamodel.py
- src/oaklib/datamodels/search_datamodel.yaml
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- tests/test_implementations/test_sqldb.py
- Adding additional documentation for conversion to FHIR
- Adding ability to search by mapping ID (e.g xref)
> Adding additional documentation for conversion to FHIR.

- src/oaklib/cli.py
- src/oaklib/converters/data_model_converter.py
- src/oaklib/converters/logical_definition_flattener.py
- src/oaklib/converters/obo_graph_to_fhir_converter.py
- src/oaklib/converters/obo_graph_to_obo_format_converter.py
- src/oaklib/converters/obo_graph_to_rdf_owl_converter.py
- src/oaklib/implementations/funowl/funowl_implementation.py
- src/oaklib/implementations/obograph/obograph_implementation.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/sparql/abstract_sparql_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/interfaces/dumper_interface.py
- tests/test_converters/test_obo_graph_to_fhir.py
Updates
```
FHIR
- OboGraphToFHIRConverter: Added 'retention' param (Include all edges, or just some specific ones?) to relevant methods.
- Misc: Minor codestyle / docstring updates.
General
- .gitignore: Added .DS_Store. Organized into sections: (i) directories, (ii) dot files, (iii) related dirs/files/patterns
```
Also includes:
- https://github.com/INCATools/ontology-access-kit/pull/373
Has some updates for:
- https://github.com/INCATools/ontology-access-kit/issues/369
> FHIR updates

- src/oaklib/cli.py
> Docstring fix for `diff-via-mappings`

- docs/intro/tutorial02.rst
- docs/intro/tutorial07.rst
- src/oaklib/cli.py
- src/oaklib/implementations/sparql/abstract_sparql_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/obograph_interface.py
- src/oaklib/interfaces/patcher_interface.py
- src/oaklib/utilities/validation/lint_utils.py
- tests/input/lint-test.obo
- tests/test_cli.py
- tests/test_validation/test_lint_utils.py
Fixes #408
From hacking with @dosumis, he would like to show this functionality at HCA workshop
> Adding --show-migration-relationships option to obsoletes command.

- src/oaklib/cli.py
> Update documentation, fixes #420

- src/oaklib/implementations/gilda.py
> Maintains no-banana zone.

- src/oaklib/datamodels/obograph.py
- src/oaklib/datamodels/obograph.yaml
- tests/test_datamodels/test_obograph_datamodel.py
> Restoring edge meta in obograph datamodel.

- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/implementations/sqldb/sqlite_utils.py
- tests/test_implementations/test_sqldb.py
- tox.ini
See https://stackoverflow.com/questions/75316741/attributeerror-engine-object-has-no-attribute-execute-when-trying-to-run-sq
Fixes #443
> Ensure sqldb is sqlalchemy-2.x compatible.

- docs/guide/aliases.rst
- docs/guide/curies-and-uris.rst
- docs/guide/primary-labels.rst
- docs/guide/relationships-and-graphs.rst
- docs/howtos/write-a-plugin.rst
- docs/intro/tutorial02.rst
- notebooks/Monarch/Mondo-phenotypic-series-genes.ipynb
- src/oaklib/__init__.py
- src/oaklib/implementations/__init__.py
- src/oaklib/selector.py
- tests/test_cli.py
- tests/test_converters/test_logical_definition_flattener_converter.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_pronto.py
- tests/test_implementations/test_sparql.py
- tests/test_utilities/test_boomer_utils.py
- tests/test_utilities/test_cross_ontology_diff.py
- tests/test_validation/test_disjointness_rule.py
- tests/test_validation/test_lint_utils.py
- removed pre ClassResolver code, #489
- Documenting and simplifying ClassResolver mechanism.
> Simplify and document ClassResolver mechanism. Fixes #489

- src/oaklib/interfaces/differ_interface.py
> fix bug caused by EdgeDeletionnot matching other edge changes.

- src/oaklib/cli.py
Now that INCATools/ontology-access-kit#501 is merged I thought I'd finish the job of adding `finish()`.
I didn't change `diff_via_mappings()` because I wasn't sure how to test it.
> Add writer.finish() to remaining cli.py commands

- .github/workflows/main.yaml
> Unpin poetry version in GH Actions

- src/oaklib/implementations/sqldb/sql_implementation.py
> Replaced `simple_mappings_by_curie` to call `sssom_mappings`

- src/oaklib/converters/obo_graph_to_rdf_owl_converter.py
- src/oaklib/datamodels/obograph.py
- src/oaklib/datamodels/obograph.yaml
See https://github.com/geneontology/obographs/issues/65
> Adding property_type node to obograph schema.

- poetry.lock
- pyproject.toml
- src/oaklib/implementations/semsimian/semsimian_implementation.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_semsimian_implementation.py
- Refactoring semsimian implementation
- more informative fail messages
- new tests and temp disabling some
- lint
> refactoring semsim implementation

- .gitignore
- Makefile
- src/oaklib/implementations/semsimian/profiler.py
> Add benchmarking for `semsimian`

- src/oaklib/interfaces/text_annotator_interface.py
> TextAnnotator: Reuse lexical index cache between calls. #573

- poetry.lock
- pyproject.toml
- src/oaklib/cli.py
- src/oaklib/implementations/semsimian/semsimian_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/semsim_interface.py
- tests/test_implementations/test_semsimian_implementation.py
Note that semsimian 0.1.14 is not on pypi yet
> Update to use semsimian 0.1.14 with better optimized semsim stuff 

- src/oaklib/cli.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/utilities/lexical/lexical_indexer.py
- src/oaklib/utilities/subsets/value_set_expander.py
- tests/input/three-way-mapping.obo
- tests/input/three-way-mapping.owl.ttl
- tests/test_utilities/test_sssom_matcher.py
- use mappings in both directions for lexical index. Fixes #585
- adding test for #585
> modify lexmatch to utilize xrefs in both directions #585

- src/oaklib/implementations/ontoportal/ontoportal_implementation_base.py
> Workaround for ontoportal prefix issue 592

- docs/glossary.rst
- docs/guide/learning-more.rst
- docs/guide/primary-labels.rst
- notebooks/Clinical/OMOP-Example.ipynb
- Extended glossary
- Added to clinical notebooks
> Additional documentation

- src/oaklib/cli.py
- src/oaklib/datamodels/association.py
- src/oaklib/datamodels/association.yaml
- src/oaklib/implementations/__init__.py
- src/oaklib/implementations/amigo/amigo_implementation.py
- src/oaklib/implementations/ncbi/ncbi_gene_implementation.py
- src/oaklib/implementations/uniprot/uniprot_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/interfaces/dumper_interface.py
- src/oaklib/utilities/keyval_cache.py
- src/oaklib/utilities/table_filler.py
- tests/input/uniprot-P12345.json
- tests/test_implementations/test_ncbigene.py
- tests/test_implementations/test_uniprot.py
Added ability to query gene associations from NCBI
Added ability to query amigo for terms and relationships
> Enhanced implementations for remote endpoints.

- docs/howtos/use-llms.rst
- docs/packages/implementations/llm.rst
- notebooks/GO/Term-Usage-Summary.ipynb
- src/oaklib/cli.py
- src/oaklib/datamodels/class_enrichment.py
- src/oaklib/datamodels/class_enrichment.yaml
- src/oaklib/implementations/agrkb/agrkb_implementation.py
- src/oaklib/implementations/amigo/amigo_implementation.py
- src/oaklib/implementations/llm_implementation.py
- src/oaklib/interfaces/association_provider_interface.py
- tests/test_implementations/test_amigo.py
- tests/test_implementations/test_sqldb.py
- Additional LLM documentation
- Additional LLM implementations
> Extending amigo and llm implementations

- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/interfaces/differ_interface.py
- src/oaklib/utilities/writers/change_handler.py
This change handling for markdown format did not exist before. Also added old value for definition in the class.
> Handle `RemoveTextDefinition`

- src/oaklib/implementations/amigo/amigo_implementation.py
- src/oaklib/interfaces/association_provider_interface.py
- src/oaklib/utilities/lexical/synonymizer.py
- src/oaklib/utilities/writers/change_handler.py
- tests/test_utilities/test_synonymizer.py
- tox.ini
`change-handler.py` is the only file that needs review. The rest are all `black` formatted files
> Ran formatter and minor code cleanup

- src/oaklib/implementations/semsimian/semsimian_implementation.py
- src/oaklib/interfaces/association_provider_interface.py
- src/oaklib/interfaces/semsim_interface.py
- tests/test_implementations/__init__.py
> More efficient association-based IC calculation.

- docs/guide/associations.rst
- pyproject.toml
See also https://github.com/OBOAcademy/obook/issues/500
> Adding link to ontogenesis chapter on annotations.

- docs/datamodels/index.rst
- docs/examples/AdHoc/ValueSets.ipynb
- docs/examples/AdHoc/index.rst
- src/oaklib/utilities/subsets/value_set_expander.py
Added an example notebook for `vskit expand`, and linked the configuration data model docs
> Value Set examples and docs
