- .github/workflows/main.yaml
- poetry.lock
- pyproject.toml
- src/oaklib/utilities/graph/networkx_bridge.py
Bump up the minimum version of Python that is required by the package to 3.9.
* A fix was necessary for one of the tests that was using `collections.Iterable` since Python 3.10 had a realignment of `collections` modules.
> bump up Python version to 3.9

- .gitignore
- docs/concepts.rst
- src/oaklib/implementations/bioportal/bioportal_implementation.py
- tests/test_implementations/test_bioportal.py
This method uses the [`/ontologies/:ontology/classes/:cls/mappings` endpoint](https://data.bioontology.org/documentation#Mapping) to get mappings and reformats them in SSSOM format.
Caveats:
* The BioPortal API has an [issue](https://github.com/ncbo/ontologies_linked_data/issues/117) where a lot of duplicate mappings are reported. We are not trying to resolve that duplication here and instead just passing the results through.
* The BioPortal API reports a `source` field for each mapping and we are manually translating that to a SKOS term, but this may be up for refinement
* The method will accept a CURIE as defined by the `MappingProviderInterface` but since the BioPortal API generally deals with URIs and not CURIEs the SSSOM `subject_id` and `predicate_id` fields will be URIs
> Add get_sssom_mappings_by_curie to BioportalImplementation class

- docs/intro/tutorial01.rst
> Add missing param flag for set-apikey in tutorial

- docs/intro/tutorial02.rst
Just to get rid of the misleading stub (the test for pronto in oak seems to use outdated paths for the pronto implementation and does not work, at least not for me).
> Adding a few boilerplate examples to programming tutorial

- README.md
- docs/intro/tutorial01.rst
- docs/intro/tutorial02.rst
- docs/intro/tutorial04.rst
- docs/intro/tutorial05.rst
- docs/introduction.md
- src/oaklib/implementations/sqldb/sql_implementation.py
This PR is a first pass at tidying up the tutorials after going through most of them.
This PR also fixes a bug in `SqlImplementation.__post_init__()` method, without which the examples in the tutorial (`README.md` and `introduction.md`) wouldn't work.
Questions:
- I see we are using Sphinx for documentation. Are we committed to Sphinx/reST?
- Can we look into MkDocs, since it has typically been used in most of our Python projects?
> Tidy up tutorials

- .github/CODE_OF_CONDUCT.md
- README.md
Closes #123
This PR adopts the [Contributor Covenant](https://www.contributor-covenant.org) as a simple yet effective code of conduct for this project. It names @cmungall as the contact person for issue resolution. This PR also adds the related badge to the README and mentions that contributors are responsible for upholding this COC
> Add Contributor Covenant as Code of Conduct

- src/oaklib/__init__.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/selector.py
- tests/test_cli.py
- When using pystow, do not use as_uri as this prepends `file:` breaking sqlite locator. Fixes #166
- comvenience path
- More graceful merge of #164 and #152
> Fix for #166

- src/oaklib/cli.py
- src/oaklib/utilities/label_utilities.py
- src/oaklib/utilities/mapping/cross_ontology_diffs.py
- tests/test_utilities/test_cross_ontology_diff.py
- ensuring the correct logger is used when setting verbosity. Fixes #180
- Adding labeling to diff-via-mapping
> adding --add-labels option to diff-via-mapping

- poetry.lock
- pyproject.toml
- tests/test_implementations/test_pronto.py
Using latest pronto which fixes https://github.com/althonos/pronto/issues/178,
this allows more ontologies to be dumped as obo
> Bumping pronto version to 2.5.0.

- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/utilities/basic_utils.py
This moves the method to get curie prefixes from the sql implementation to a general method that can be used everywhere
> Centralizing get_curie_prefix

- src/oaklib/cli.py
- src/oaklib/implementations/ubergraph/ubergraph_implementation.py
- src/oaklib/io/streaming_csv_writer.py
- src/oaklib/io/streaming_writer.py
- src/oaklib/io/streaming_yaml_writer.py
- src/oaklib/utilities/obograph_utils.py
- tests/test_utilities/test_obograph_utils.py
Example:
```
✗ go paths  -p i,p --no-autolabel 'nuclear membrane' --target cytoplasm
subject object  paths
GO:0031965      GO:0005737      ['GO:0031965', 'GO:0005635', 'GO:0012505', 'GO:0110165', 'GO:0005737']
GO:0031965      GO:0005737      ['GO:0031965', 'GO:0031090', 'GO:0016020', 'GO:0110165', 'GO:0005737']
```
```
✗ go paths  -p i,p 'nuclear membrane' --target cytoplasm
subject object  paths   subject_label   object_label    paths_label
GO:0031965      GO:0005737      ['GO:0031965', 'GO:0005635', 'GO:0012505', 'GO:0110165', 'GO:0005737']  nuclear membrane        cytoplasm       nuclear membrane | nuclear envelope | endomembrane system | cellular anatomical entity | cytoplasm
GO:0031965      GO:0005737      ['GO:0031965', 'GO:0031090', 'GO:0016020', 'GO:0110165', 'GO:0005737'] …
```
> Adding shortest paths util

- poetry.lock
- pyproject.toml
It's getting out of hand trying to keep up with locking in #127 - I'm sure we will use this requirement soon, and it is a pure python package (i.e., has no requirements itself) so this merge shouldn't be too controversial
> Add `class-resolver` as requirement

- src/oaklib/implementations/pronto/pronto_implementation.py
- tox.ini
Reverts INCATools/ontology-access-kit#215
Previous iteration #209 assumed all synonyms to be `RELATED`. Now this can be derived from the command using the following code:
```
scope = str(patch.qualifier.value).upper() if patch.qualifier else "RELATED"
t.add_synonym(description=patch.new_value, scope=scope)
```
> Revert "Get 'scope' information from the command."

- README.md
First I fixed a typo (it's -> its) but then I started making the list of operations more consistent. 
I removed "ontology term matching" after first changing it to "find matching terms" and concluding that was basically the same as "search an ontology for a term", but maybe there's something I'm missing.
> minor changes for consistency and readability

- src/oaklib/io/streaming_json_writer.py
Fixes #213 
Command:
```
runoak -i hp.obo descendants HP:0000005 -p i,p -O json
```
now yields a result and does not error out as mentioned in #213
> JSON Writer now outputs nodes in JSON format

- docs/intro/tutorial07.rst
Updates
```
Update tutorial07.rst
Added tutorial documentation for running semsql on OWL files without docker.
```
> Docs: semsql from OWL w/out docker

- .github/workflows/main.yaml
- src/oaklib/implementations/ontoportal/ontoportal_implementation_base.py
- tests/test_implementations/test_bioportal.py
These changes allow passing an API key to `OntoPortalImplementationBase` classes. Then in `test_bioportal.py`, first the standard `get_apikey_value` function is called to get a key (this mainly supports running tests locally). If no API key is found that way, it will check for an environment variable named `BIOPORTAL_API_KEY` (this will be provided via repo secret when running via GitHub Actions). If neither method produces an API key the tests will be skipped.
> Allow BioPortal tests to run in GitHub Actions

- README.md
- src/oaklib/utilities/apikey_manager.py
Using oak in schema_automator to access bioportal with BIOPORTAL_API_KEY set in the ENV.
> Add a check of ENV variables to the apikey_manager.get_apikey_value method  fixes #262

- .github/workflows/main.yaml
- tests/test_implementations/test_bioportal.py
The tests were running twice, which is wasteful of compute resources and slow. This PR combines them together. It also switches from unittest to pytest, which makes it much easier to look through the logs
> Combine coverage analysis

- src/oaklib/implementations/__init__.py
- src/oaklib/resource.py
- src/oaklib/selector.py
These changes move the construction of the `ClassResolver` instance for implementation classes into a function. This allows the loading of entry point classes to be delayed until one is actually needed. And that should make it a lot harder to get into the circular import / partially initialized module trap. The function is memoized so only one `ClassResolver` instance is ever created.
Fixes #280
> Delay construction of ClassResolver instance

- src/oaklib/interfaces/basic_ontology_interface.py
Updates
```
Bugfix: basic_ontology_interface
- Bugfix: hierararchical_parents(): If no parents found, now returns an empty list rather than resulting in `KeyError`.
```
> Bugfix: basic_ontology_interface

- poetry.lock
- pyproject.toml
- tests/test_implementations/test_gilda.py
This fixes #300 
Problem: By default an older SciPy version (dependency of a dependency) is installed (v1.6.1) which does not play well with python v3.10. So I add it as a direct dependency and anchor it to `>=1.9.1`. On doing that, there is a complain raised stating the project python version compatibility is from 3.9 to 4 but with the scipy version installed it is 3.9 to 3.12. So I set python version window between 3.9 and 3.12 and now everything seems to be okay.
This window will need to be revisited while supporting future version of python.
> Fix py version window & provide minimum scipy version

- src/oaklib/utilities/lexical/lexical_indexer.py
This fixes https://github.com/monarch-initiative/mondo-ingest/issues/95. Earlier when lexmatch changed labels based on `match-rules.yaml` , the `mapping_justification` was assigned the value `"semapv:RegularExpressionReplacement"` which is incorrect. This value should be assigned to either `subject_preprocessing` or `object_preprocessing` based on the term relevance.
> RegularExpressionReplacement from mapping_justification to preprocessing

- src/oaklib/implementations/sqldb/sql_implementation.py
This will ensure faster downloads for large databases;
it also means we can start phasing out the direct .db deposits
and save s3 space.
Utilizes https://github.com/cthoyt/pystow/issues/45
Note that the gzipped file is not cached in ~/.data - but
the gunzipped file is. It is necessary for the user
to periodically clean this cache.
See https://github.com/cthoyt/pystow/issues/54
> Use the gzipped file from the semsql s3 cache.

- .github/workflows/main.yaml
- poetry.lock
- pyproject.toml
- src/oaklib/implementations/simpleobo/simple_obo_parser.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/implementations/sqldb/sqlite_utils.py
- src/oaklib/selector.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_gilda.py
- tests/test_utilities/test_sqlite_utils.py
This PR includes several fixes to make the test suite pass on windows. It also adds Windows to the CI tests.
csv-files were loaded to sqlite by shell commands which do not work in the typical Windows environment. I replaced this by using pandas for reading csv and writing to sqlite. pandas was already an indirect dependency (via sssom) so I thought it is OK to use. Because the old code had links to stackoverflow that indicated the importance of bulk-uploading of large files, I added the option to load csv in chunks. 
So far I have kept the old function `sqlite_bulk_load` in `src/oaklib/implementations/sqldb/sqlite_utils.py` but its code is gone and it calls the new `sqlite_bulk_load2`. However, if the function is not used elsewhere we could replace the old one entirely by the new function …
> Windows fixes (make test suite pass on windows)

- poetry.lock
- src/oaklib/cli.py
- src/oaklib/datamodels/ontology_metadata.py
- src/oaklib/datamodels/ontology_metadata.yaml
- src/oaklib/datamodels/validation_datamodel.py
- src/oaklib/datamodels/validation_datamodel.yaml
- src/oaklib/utilities/validation/definition_ontology_rules.py
- src/oaklib/utilities/validation/ontology_rule.py
Adding options to --validate-definitions
> Switch default output for ancestors to be csv; throw exception if info writer combined with statistics. Fixes #354

- Makefile
- src/oaklib/cli.py
- src/oaklib/converters/data_model_converter.py
- src/oaklib/converters/logical_definition_flattener.py
- src/oaklib/converters/obo_graph_to_fhir_converter.py
- src/oaklib/converters/obo_graph_to_rdf_owl_converter.py
- src/oaklib/datamodels/fhir.py
- src/oaklib/datamodels/fhir.yaml
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/dumper_interface.py
- src/oaklib/interfaces/obograph_interface.py
- src/oaklib/io/streaming_fhir_writer.py
- src/oaklib/utilities/obograph_utils.py
- tests/test_cli.py
- tests/test_converters/test_obo_graph_to_fhir.py
> Adding FHIR CodeSystem dumping.

- src/oaklib/cli.py
- src/oaklib/conf/value-set-expander.conf.yaml
- src/oaklib/datamodels/value_set_configuration.py
- src/oaklib/datamodels/value_set_configuration.yaml
- src/oaklib/implementations/obograph/obograph_implementation.py
- src/oaklib/implementations/sparql/abstract_sparql_implementation.py
- src/oaklib/interfaces/dumper_interface.py
- src/oaklib/interfaces/obograph_interface.py
- src/oaklib/utilities/subsets/value_set_expander.py
- tests/input/value_set_example.yaml
- tests/test_cli.py
- tests/test_utilities/test_value_set_expander.py
Fixes:
-  #370
This PR adds a new top level command (name is not yet final) called vskit:
```
vskit expand  --help
Usage: vskit expand [OPTIONS] [VALUE_SET_NAMES]...
Expand a value set. EXPERIMENTAL.
This will expand an *intensional value set* (aka *dynamic enum*), running a
query against an ontology backend or backends to materialize the value set
(permissible values).
Currently the value set must be specified as LinkML, but in future this will
be possible with other specifications such as FHIR ValueSet objects.
Each expression in a dynamic enum has a *source ontology*, this is specified
as a CURIE such as:
- obo:mondo - bioregistry:wikidata
These can be mapped to specific OAK selectors. By default, any obo prefix is
mapped to the semsql implementation of that. You can use a …
```
> Adding a valueset toolkit, performs expansion.

- .gitignore
Updates
- .gitignore: Added .DS_Store. Organized into sections: (i) directories (ii) dot files, (iii) related dirs/files/patterns
> gitignore: `.DS_Store`, etc

- src/oaklib/datamodels/search_datamodel.py
- src/oaklib/interfaces/text_annotator_interface.py
When a function yields results and this function is called another function that is also intended to yield results of an iterable, the calling function uses `yields from` This is offered by python versions > 3.3. This is called [generator delegation](https://docs.python.org/3/whatsnew/3.3.html).
Fixes #376
> yield results from a generator fixes  #376

- src/oaklib/cli.py
- src/oaklib/utilities/lexical/lexical_indexer.py
- tests/test_cli.py
> Pass `prefix_map` to `lexmatch` output and clean the same before generating SSSOM output

- src/oaklib/cli.py
- src/oaklib/implementations/obograph/obograph_implementation.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/implementations/translator/translator_implementation.py
- src/oaklib/interfaces/mapping_provider_interface.py
- src/oaklib/selector.py
- src/oaklib/utilities/mapping/sssom_utils.py
- tests/test_implementations/test_translator.py
Example usage:
`runoak  -i translator: mappings NCBIGene:1588 MONDO:0005180 -O sssom`
output:
|subject_id|subject_label|predicate_id|object_id|object_label|mapping_justification|subject_source|object_source|
|---|---|---|---|---|---|---|---|
|MONDO:0005180|Parkinson disease|skos:exactMatch|DOID:14330|Parkinson's disease|semapv:ManualMappingCuration|MONDO|DOID|
|MONDO:0005180|Parkinson disease|skos:exactMatch|SNOMEDCT:49049000||semapv:ManualMappingCuration|MONDO|SNOMEDCT|
|MONDO:0005180|Parkinson disease|skos:exactMatch|NCIT:C26845|Parkinson's Disease|semapv:ManualMappingCuration|MONDO|NCIT|
|MONDO:0005180|Parkinson disease|skos:exactMatch|MEDDRA:10061536||semapv:ManualMappingCuration|MONDO|MEDDRA|
|MONDO:0005180|Parkinson disease|skos:exactMatch|MEDDRA:10034008||semapv:ManualMappingCuratio …
> Adding a Translator Node Normalizer adapter. Fixes #397

- src/oaklib/converters/obo_graph_to_fhir_converter.py
- src/oaklib/datamodels/fhir.py
- src/oaklib/datamodels/fhir.yaml
- tests/test_converters/test_obo_graph_to_fhir.py
Updates
```
FHIR
- Add: unit tests for specific ontologies
- Add: unit test helpers to download and use cache
- Update: LinkML: CodeSystemProperty
- Update: OboGraph to FHIR Converter: Now populates CodeSystem.property
```
> FHIR: CodeSystem.property

- src/oaklib/cli.py
- src/oaklib/datamodels/ontology_metadata.py
- src/oaklib/datamodels/ontology_metadata.yaml
- src/oaklib/datamodels/vocabulary.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_parser.py
- src/oaklib/interfaces/basic_ontology_interface.py
- src/oaklib/interfaces/metadata_interface.py
- src/oaklib/interfaces/obolegacy_interface.py
- src/oaklib/interfaces/patcher_interface.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_simple_obo.py
This centralizes operations for mapping to legacy obo concepts,
such as shorthands for predicate CURIEs.
TYhis PR also adds a undo options to the patcher interface
> Added OboLegacyInterface.

- .gitattributes
- .github/workflows/main.yaml
The bug can be seen here: https://github.com/INCATools/ontology-access-kit/actions/runs/4209345211/jobs/7306256452
Same fix as in https://github.com/linkml/linkml/pull/1202
> Fix non-stopping CI on windows

- poetry.lock
- pyproject.toml
Pystow just released an update which shows a tqdm progress bar during downloads, 
which we implement in monarch-py / monarch-api
Unfortunately, there's a poetry version resolution issue as oaklib's required version is^0.4.4
This PR just looks to update oaklib's requirement so that monarch-api can install successfully
> update pystow to 0.5.0, shows progress bar on download

- src/oaklib/parsers/__init__.py
- src/oaklib/parsers/phaf_association_parser.py
- tests/input/test.phaf.tsv
- tests/test_parsers/test_phaf_association_parser.py
Addresses #474
Includes the parser and analogous test to that in `tests/test_parsers/test_hpoa_association_parser.py`
> PHAF parser and tests added

- src/oaklib/implementations/aggregator/aggregator_implementation.py
- tests/test_cli.py
This is useful to choose appropriate `annotate_text()` and `annotate_file()` methods depending on the implementation type.
> Add `annotate_text()`and `annotate_file()` methods to `AggregatorImplementation`

- README.md
- docs/implementations/bioportal.rst
- src/oaklib/cli.py
- src/oaklib/datamodels/lexical_index.py
- src/oaklib/datamodels/lexical_index.yaml
- src/oaklib/datamodels/mapping_rules_datamodel.yaml
- src/oaklib/implementations/__init__.py
- src/oaklib/implementations/kgx/kgx_implementation.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/implementations/sparql/sparql_implementation.py
- src/oaklib/interfaces/__init__.py
- src/oaklib/interfaces/text_annotator_interface.py
- src/oaklib/selector.py
- src/oaklib/utilities/lexical/lexical_indexer.py
- tests/input/matcher_rules.yaml
- tests/test_implementations/__init__.py
- tests/test_implementations/test_pronto.py
- tests/test_implementations/test_simple_obo.py
- tests/test_implementations/test_sparql.py
- tests/test_implementations/test_sqldb.py
- tests/test_utilities/test_lexical_index.py
* synonymizer refactor
- no longer uses `eval`
- this will break some synonymizer configs
- previously they had some regexes like `r'...'`.
- these should be changed to be a direct yaml string encoding of the regex
- we can increment the minor version of OAK for this
* text annotator enhancements
- allow caching of lexical indexes between runs (@vemonet this should help with some of the speed issues in ontogpt)
* documentation
- made the README a bit more developer-friendly
> synonymizer refactor

- src/oaklib/cli.py
- src/oaklib/io/streaming_writer.py
- src/oaklib/utilities/mapping/sssom_utils.py
- tests/test_cli.py
(Replaces INCATools/ontology-access-kit#498)
This fixes invalid JSON output from some commands defined in `cli.py`. The closing "]" was missing with "-O json".
For example, both of these commands produce invalid JSON:
```
runoak -i bioportal: annotate -O json "enlarged nucleus in T-cells from peripheral blood"
```
```
runoak -i sqlite:obo:fypo aliases -O json FYPO:0009021
```
This PR is my guess at a fix for annotation(), aliases(), mappings(), ancestors(), descendants() and similarity_pair().
> Add missing writer.finish() to commands in cli.py

- docs/howtos/fhir-conversions.rst
- docs/howtos/index.rst
- src/oaklib/cli.py
- src/oaklib/converters/obo_graph_to_fhir_converter.py
- src/oaklib/datamodels/fhir.yaml
- tests/input/fhir_config_example.json
- tests/input/hp_test.json
- tests/test_cli.py
- tests/test_converters/test_obo_graph_to_fhir.py
- tests/test_implementations/test_ols.py
Updates
```
commit 0fe7a343c52975259d8e944e291a1c9ef4c89614 (HEAD -> fhir-updates-2)
Obograph to FHIR updates
- use_curies_foreign_concepts: default changed to True
- test cases: updated release URIs
- bugfix: IDs needed to be formatted in a different way
commit accb465957e2cd92cc3da5ac0fdd118508a2cb4c
FHIR
- Update: Changed concept references from CURIEs to codes (for native concepts) or URIs (for foreign concepts) by default.
- Update: Removed @type appearing in CodeSystem output
- Add: param: code_system_url
- Add: param: code_system_id
FHIR work-in-progress:
- Add: param use_curies_native_concepts to allow for CURIEs for native concept references (WIP)
- Add: param use_curies_foreign_concepts to allow for CURIEs for foreign concept references (WIP)
- Add: param native_uri_stems to …
```
> More FHIR updates

- tests/__init__.py
- tests/test_implementations/test_pronto.py
- tests/test_implementations/test_simple_obo.py
- tox.ini
Observed failures:
```
========================== short test summary info ========================== 
FAILED tests/test_cli.py::TestCommandLineInterface::test_statistics - AssertionError: 0 != 1
FAILED tests/test_implementations/test_simple_obo.py::TestSimpleOboImplementation::test_sort_order_no_edits - AssertionError: False is not true
FAILED tests/test_implementations/test_sqldb.py::TestSqlDatabaseImplementation::test_summary_statistics - ModuleNotFoundError: No module named 'pwd'
```
One failure was related to missing env vars (tox clears them). The others were related to filecomp.cmp which does compare files in binary mode. So text files with the same content but different EOL chars compared as different. I added a version to compare files ignoring EOL chars.
> Fix testing with tox on windows

- src/oaklib/cli.py
- src/oaklib/implementations/pronto/pronto_implementation.py
- src/oaklib/interfaces/association_provider_interface.py
- src/oaklib/interfaces/class_enrichment_calculation_interface.py
- src/oaklib/parsers/__init__.py
- src/oaklib/parsers/association_parser_factory.py
This PR adds the ability to do an ontology-only pseudoenrichment. This can be useful for quickly summarizing a term list to a set of grouping terms that 'best' stratify the set.
E.g. given:
```
$ cat terms.txt
id	label
UBERON:0000955	brain
UBERON:0001466	pedal digit
UBERON:0002136	hilus of dentate gyrus
UBERON:0002389	manual digit
UBERON:0002928	dentate gyrus polymorphic layer
UBERON:0003881	CA1 field of hippocampus
UBERON:0003882	CA2 field of hippocampus
UBERON:0003883	CA3 field of hippocampus
UBERON:0003884	CA4 field of hippocampus
UBERON:6110636	insect adult cerebral ganglion
UBERON:0001238	lamina propria of small intestine
UBERON:0001239	muscularis mucosae of large intestine
UBERON:0001240	muscularis mucosae of intestine
UBERON:0001241	crypt of Lieberkuhn of small intestine …
```
> ontology only enrichment

- src/oaklib/implementations/rustsim/rustsim_implementation.py
* Fix NotImplementedError when using search with RustsimImplementation
* Use the `get_adapter` function for RustsimImplementation
> Fixes for RustsimImplementation not completing search-based similarities

- src/oaklib/io/streaming_yaml_writer.py
> Leave keys unsorted when exporting yaml

- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
Here, I'm replacing the definition entirely to "".
Example command:
```
remove definition for FBbt:00000001
```
Implements https://github.com/INCATools/kgcl/pull/28
> Slight addition to handle KGCL `RemoveTextDefinition`

- src/oaklib/cli.py
> Make `ensure_strict_prefixes` default to `False` in `lexmatch`

- poetry.lock
- pyproject.toml
- src/oaklib/datamodels/similarity.owl.ttl
- src/oaklib/datamodels/similarity.py
- src/oaklib/datamodels/similarity.yaml
- src/oaklib/implementations/semsimian/semsimian_implementation.py
Fixes #642 
In addition to formatting `float` values and `NaN` => `None`
- After which I ran `make similarity.py` and `make similarity.owl.ttl` 
- Relevant PR: https://github.com/monarch-initiative/semsimian/pull/90
> Output for semsimian's `termset_pairwise_similarity` formatted correctly

- src/oaklib/cli.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
Fixes #654
Currently only implemented for sql adapter
Example usage:
```python
>>> from oaklib import get_adapter
>>> adapter = get_adapter("sqlite:obo:mondo")
>>> rels = list(adapter.relationships(["MONDO:0009831"]))
>>> for rel, metadatas in adapter.relationships_metadata(rels):
...     for p, v in metadatas:
...         print(rel, p, v)
<BLANKLINE>
...
('MONDO:0009831', 'rdfs:subClassOf', 'MONDO:0002516') oio:source NCIT:C9005
...
```
or on the command line:
```
runoak -i sqlite:obo:mondo relationships MONDO:0009831 --include-metadata -p i
```
```
> Adding ability to retrieve axiom annotations on relationships (axiom annotations)

- poetry.lock
- pyproject.toml
- src/oaklib/converters/logical_definition_flattener.py
- src/oaklib/converters/obo_graph_to_cx_converter.py
- src/oaklib/converters/obo_graph_to_fhir_converter.py
- src/oaklib/converters/obo_graph_to_obo_format_converter.py
- src/oaklib/converters/obo_graph_to_rdf_owl_converter.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
This PR uses the new version of `curies` that simplifies the expand and compress functions to be able to pass through the original value if they can't be operated on. This new feature is disabled by default, but so it is explicitly enabled in several places in OAK to demonstrate its usage
> Use passthrough from curies v0.6.6

- .github/workflows/main.yaml
This seems to be the solution for random errors in GitHub workflows due to poetry .
Another reference where this fix worked: https://github.com/mapping-commons/sssom-py/pull/433#issuecomment-1747314542
> `ChefBuildError` fix

- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/interfaces/basic_ontology_interface.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_sqldb.py
> Implemented `entities_metadata_statements()` for `SQLImplementation()`

- src/oaklib/utilities/subsets/value_set_expander.py
This PR changes how linkml dynamic enums are rendered from the `vskit` command. 
- First, the generated permissible value will always include a `title` slot with the human readable label 
- and second it will include the definition for the `description` slot. 
- the text slot remains configurable using the `pv_formula` (and this [PR](https://github.com/linkml/linkml-model/pull/171) will enable using the human readable value as the permissible value)
This would add a bit of bloat to how enums are rendered. For my use case, I want to surface enums and definitions in our linkml-based documentation, so having a definition would be useful. If that is too much bloat, it make sense to add an additional flag or configuration option for mapping properties from the `BasicOntologyInterface` to their …
> Include title and definition in vskit expand

- src/oaklib/utilities/subsets/value_set_expander.py
This is a small followup on https://github.com/INCATools/ontology-access-kit/pull/677
@nicholsn work was good, but sometimes ontologies do not have a valid value for Label/text, so this defaults to the CURIE if there is none.
> VSKit Permissible Value Label Fix

- src/oaklib/utilities/subsets/value_set_expander.py
VSKit generates "descriptions" for LinkML from ontologies. Sometimes, those descriptions contain newline characters. These newline characters break downstream LinkML tooling such as the Pydantic generator. 
I believe that it is appropriate to replace those newline characters with spaces at this point in the flow. 
An example of this newline phenomenon is the permissible value IP-seq from EFO:
```
IP-seq:
text: IP-seq
description: "IP-seq is an assay in which immunoprecipitation with high throughput\
\ sequencing is used to identify the DNA/RNA-associated proteins or protein\
\ complexes.\nAs an immunoprecipitation it can be ChIP, RIP or another immunoprecipitation\
\ process."
meaning: EFO:0005032
title: IP-seq
```
Which does not look the same as, for example, its rendering on EBI …
> VSKit  - description newline replacement

- src/oaklib/implementations/semsimian/semsimian_implementation.py
- src/oaklib/utilities/subsets/value_set_expander.py
Fixes #701
When `value_set_names` param was not provided, it was passed as an empty tuple since it accepts multiple arguments. This PR forces it to be `None` instead on `()`
> value_set_names is None rather than ()

- docs/howtos/use-llms.rst
- poetry.lock
- pyproject.toml
- src/oaklib/implementations/llm_implementation.py
- Adding docs on how to use different LLM models
- Adding exception handling to llm calls
> llm exception handling

- src/oaklib/cli.py
- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/interfaces/differ_interface.py
- src/oaklib/io/streaming_markdown_writer.py
- src/oaklib/utilities/mapping/mapping_validation.py
- src/oaklib/utilities/writers/change_handler.py
- tests/test_implementations/__init__.py
- tests/test_implementations/test_bioportal.py
- Adding a more efficient diff implementation for simpleobo
- technically this is a violation of the DRY principle but one of the goals of the interface/impl split is to allow implementations to do custom implementations that may be faster
- Undoing some of https://github.com/INCATools/ontology-access-kit/pull/605
> More efficient simple obo diffs

- Makefile
- src/oaklib/cli.py
- src/oaklib/datamodels/mapping_rules_datamodel.py
- src/oaklib/datamodels/mapping_rules_datamodel.yaml
- src/oaklib/datamodels/synonymizer_datamodel.py
- src/oaklib/datamodels/synonymizer_datamodel.yaml
- src/oaklib/datamodels/vocabulary.py
- src/oaklib/utilities/kgcl_utilities.py
- src/oaklib/utilities/lexical/lexical_indexer.py
- src/oaklib/utilities/lexical/synonymizer.py
- tests/input/cli-synonymizer-rules.yaml
- tests/input/matcher_rules.yaml
- tests/test_cli.py
- tests/test_utilities/test_lexical_index.py
- tests/test_utilities/test_synonymizer.py
- synonymizer refactoring.
- Command line
> synonymizer refactor2

- src/oaklib/utilities/writers/change_handler.py
> Added `diff` markdown for `AddNodeToSubset`

- docs/glossary.rst
- docs/guide/mappings.rst
- notebooks/Commands/Mappings.ipynb
- src/oaklib/cli.py
- src/oaklib/datamodels/mapping_rules_datamodel.py
- src/oaklib/datamodels/mapping_rules_datamodel.yaml
- added a Commands/Mappings notebook
- extended the OAK mappings guide to talk about some difficulties around directionality
- clarified how weights work in lexmatch rules
- removed duplicate synonymizer section in rules data model (it now has its own data model)
> Enriched mapping documentation

- src/oaklib/io/streaming_writer.py
- src/oaklib/utilities/publication_utils/pubdb_wrapper.py
This should not be necessary. See #756
> Make ruff happy

- src/oaklib/cli.py
- src/oaklib/conf/obograph-style.json
Allowing '@' in input options for viz, allowing separation
of highlighted terms and query terms
> Adding has-part glyph to config.

- src/oaklib/implementations/simpleobo/simple_obo_implementation.py
- src/oaklib/utilities/writers/change_handler.py
- tests/test_implementations/__init__.py
- Fixes #778
- Fixes #779 
- Fixes #732 
Resolves multiple issues:
- `ClassCreeation` was being duplicated in all output formats when the `simpleobo:` adapter was used.
- `Mappings created/removed` table in markdown format was not properly formatted.
This PR fixes both.
> Solves ClassCreation duplication & formats Mappings md table properly

- src/oaklib/utilities/writers/change_handler.py
Previously non existent. 
Triggered by: https://github.com/monarch-initiative/mondo/pull/7962#pullrequestreview-2192964282
> Added change handler for `kgcl.RemoveNodeFromSubset`

- src/oaklib/implementations/sqldb/sql_implementation.py
The current logging scheme for sql_queries directly outputs the sqlachemy query as rendered by what is the following:
```
q = session.query(...)
logging.info(str(q))
```
The following is the output from [logging.info(f"ECA query: {q}")](https://github.com/INCATools/ontology-access-kit/blob/7774d909e7231ac94347cc77cda4fe5e05b54922/src/oaklib/implementations/sqldb/sql_implementation.py#L1083) in function[ _equivalent_class_relationships](https://github.com/INCATools/ontology-access-kit/blob/7774d909e7231ac94347cc77cda4fe5e05b54922/src/oaklib/implementations/sqldb/sql_implementation.py#L1067).
```
INFO:root:ECA query: SELECT statements.subject AS statements_subject, statements.predicate AS statements_predicate, statements.object AS statements_object FROM statements
WHERE statements.predicate …
```
> Update sql_implementation.py to include sqlachemy output in debug logging.

- tests/test_cli.py
- tests/test_implementations/test_semsimian_implementation.py
- tests/test_selector.py
This PR fixes two issues with the test suite.
The first (#794) is that the test suite fails if `gilda` and/or `semsimian` are not installed in the environment, even though those modules are _optional_ dependencies and as such not installed by a standard `poetry install` command. This PR fixes that by detecting the absence of those modules and skipping the corresponding tests, instead of letting them fail.
The second (#795) is that the `test_annotate_file` file may fail because of unexpected warnings emitted by the `annotate` command, even if the command runs normally and produces the expected output file. This PR fixes that by making the test ignore any `WARNING` line when checking the STDERR output of the command.
(That second fix  is based on the assumption that we don’t actually care …
> Fix test suite

- poetry.lock
- pyproject.toml
- src/oaklib/implementations/semsimian/semsimian_implementation.py
- tests/test_cli.py
When `len(ancestor_set) == 0` the jacquard and AIC scores are explicitly set to 0 which is incorrect. 
Thank you @souzadevinicius  for highlighting this!
Also updated `semsimian` version dependency to latest
fixes https://github.com/monarch-initiative/semsimian/issues/133#issuecomment-2286663198
> Bug in calculating `all_by_all_pairwise_similarity`

- tests/test_implementations/test_semsimian_implementation.py
> Add test for all_by_all_pairwise_similarity() in semsimian using custom IC map

- docs/cli.rst
- docs/intro/tutorial07.rst
- src/oaklib/cli.py
- src/oaklib/constants.py
- src/oaklib/implementations/llm_implementation.py
- src/oaklib/implementations/sqldb/sql_implementation.py
- src/oaklib/utilities/caching.py
- tests/input/cache.conf
- tests/test_utilities/test_caching.py
This PR implements roughly what was proposed in [this comment](https://github.com/INCATools/ontology-access-kit/issues/792#issuecomment-2292350550).
From a user’s perspective:
By default, whenever an attempt is made to access a SQLite DB through the `sqlite:obo:...` descriptor, and the requested DB is already present in the Pystow cache, OAK will check whether the SQLite file is older than 7 days, and if it is, will forcefully re-download that file again.
A new command-line global option `--caching` is available to alter that default behaviour. That option allows to:
* Change the duration after which a cached DB is considered “stale” and in need of refreshing; for example, with `--caching=3w`, a cached DB will be refreshed upon access if is older than 3 weeks (the general syntax is `ND`, …
> Add cache management features

- docs/howtos/use-oak-expression-language.rst
- src/oaklib/query.py
> Adding a .sample operator

- docs/guide/mappings.rst
- docs/guide/relationships-and-graphs.rst
- docs/intro/tutorial06.rst
- docs/intro/tutorial08.rst
- docs/packages/interfaces/index.rst
The owl tutorial has an outdated warning about a PR that needed merging in one of the dependencies:
https://github.com/INCATools/ontology-access-kit/blob/main/docs/intro/tutorial06.rst?plain=1#L4
The warning mentions v0.3.0 of OAK so I'm guessing it's safe to assume that changes have been made and only this documentation artefact remains.
This PR removes that warning and fixes a few minor typos that I noticed whilst going through the tutorial.
> Remove outdated warning, fix minor typos

- src/oaklib/implementations/ontoportal/ontoportal_implementation_base.py
- tests/test_implementations/test_bioportal.py
This commit adds two key methods to the OntoportalImplementationBase class:
1. entities(): Implements the entities() method from BasicOntologyInterface
- Adds pagination support to handle large ontologies
- Caches labels to improve performance for future queries
- Properly handles error cases
2. node(): Implements the node() method from OboGraphInterface
- Retrieves detailed information about ontology entities
- Properly formats synonyms respecting the ScopeEnum expectations
- Supports metadata collection for definitions, properties, etc.
These improvements enable better interoperability with other OAK tools
that rely on these interface methods, allowing users to work with BioPortal
and other OntoPortal-based systems more effectively.
Added tests for both methods including mock tests to …
> Extend OntoportalImplementation with entities() and node() methods
